theme: jekyll-theme-slate
name: "cars"
output_dir: "/"
navbar:
  title: "Cars"
  left:
  - text: "Home"
   href:speed-and-cars.html
  - text: "Speed and Distance"
   href: speed-and-cars.html
output:
  html_document:
 theme: cosmo
