theme: jekyll-theme-slate
name: "cars"
output_dir: "docs"
navbar:
  title: "Cars"
  left:
  - text: "Home"
   href: index.html
  - text: "Speed and Distance"
   href: speed-and-cars.html
output:
  html_document:
 theme: cosmo
